const plantDatabase = {
  darlingtonia: {
    title: "Darlingtonia californica",
    price: 35,
    img: "img/Darlingtonia.jpg",
    category: "carnivorous",
    desc: "Unique carnivorous plant with a cobra-like shape. Native to Northern California and Oregon, this striking species captures the imagination with its hollow hooded leaves and translucent fangs that trap foraging insects naturally.",
    height: '10" - 14" tall',
    pot: '6" Diameter',
    light: "Full Sun / Partial",
    water: "Distilled / Damp",
  },
  "hoya-carnosa": {
    title: "Hoya Carnosa",
    price: 25,
    img: "img/hoya-carnosa.jpg",
    category: "indoor",
    desc: "Classic indoor trailing plant known as the porcelain flower. It produces beautiful, wax-like star clusters of sweetly scented pinkish flowers and features thick, deep green ornamental foliage perfect for hanging baskets.",
    height: '12" - 24" vine',
    pot: '6" Diameter',
    light: "Bright Indirect",
    water: "Allow to dry out",
  },
  philodendron: {
    title: "Philodendron",
    price: 30,
    img: "img/philodendrom.jpeg",
    category: "tropical",
    desc: "Lush tropical plant featuring large, highly decorative heart-shaped leaves. Exceptionally easy to grow indoors, it brings a vibrant jungle ambiance to any living room corner while effectively purifying indoor air.",
    height: '14" - 20" tall',
    pot: '8" Diameter',
    light: "Medium Indirect",
    water: "Keep lightly moist",
  },
  syngonium: {
    title: "Pink Syngonium",
    price: 20,
    img: "img/syngonium-rosa.jpg",
    category: "indoor",
    desc: "Eye-catching indoor plant displaying stunning arrowhead leaves flushed with pastel pink hues. Compact as a young plant, it gracefully begins to trail over time, offering incredible contrast against green collections.",
    height: '8" - 12" tall',
    pot: '4" Diameter',
    light: "Bright Indirect",
    water: "Dry top inch",
  },
  "monstera-borsigiana": {
    title: "Monstera Borsigiana",
    price: 150,
    img: "img/Monstera-Borsigiana.jpg",
    category: "tropical",
    badge: "Rare Find",
    desc: "Fast-growing and iconic tropical climber highly popular worldwide. Its dramatic, large fenestrated leaves develop quickly when provided vertical support like a moss pole, creating an undeniable architectural statement.",
    height: '20" - 30" tall',
    pot: '10" Diameter',
    light: "Bright Indirect",
    water: "Water thoroughly",
  },
  "aloe-aristata": {
    title: "Aloe aristata",
    price: 15,
    img: "img/Aloe-aristata.jpg",
    category: "succulents",
    desc: "Hardy and beautifully patterned rosette succulent ideal for small indoor surfaces. Features deep green spear-shaped leaves covered in white raised bumps and soft lace-like spines along its geometric borders.",
    height: '5" - 7" tall',
    pot: '4" Diameter',
    light: "Direct / Bright",
    water: "Soak and dry completely",
  },
  maranta: {
    title: "Lemon Lime Maranta",
    price: 25,
    img: "img/maranta-lima-naranja.jpg",
    category: "indoor",
    desc: "Stunning ornamental prayer plant with spectacular bright green neon veins running across its patterned foliage. Its leaves fold upwards during night hours, resembling hands folded together in a quiet prayer posture.",
    height: '6" - 10" spreading',
    pot: '6" Diameter',
    light: "Low to Medium Indirect",
    water: "Consistently moist",
  },
  sansevieria: {
    title: "Sansevieria",
    price: 25,
    img: "img/sansevieria.jpg",
    category: "indoor",
    desc: "Unbeatably resilient snake plant characterized by rigid, sword-like jagged leaves growing upright. Renowned for surviving minimal care routines, it is the absolute perfect choice for novice plant parents.",
    height: '16" - 24" tall',
    pot: '6" Diameter',
    light: "Any light condition",
    water: "Every 2-3 weeks",
  },
  dracaena: {
    title: "Dracaena",
    price: 40,
    img: "img/Dracaena.jpg",
    category: "indoor",
    desc: "Elegant and architectural ornamental tree-like houseplant featuring narrow arched ribbon leaves clustered over a slender woody stalk. Excellent for filling vertical structural gaps inside modern offices or empty rooms.",
    height: '24" - 36" tall',
    pot: '8" Diameter',
    light: "Moderate Indirect",
    water: "Allow top half to dry",
  },
  "helecho-boston": {
    title: "Boston Fern",
    price: 30,
    img: "img/Helecho-Boston.jpg",
    category: "indoor",
    desc: "Classic lush green fern with soft arching fronds that produce a waterfall effect. Thrives beautifully in high humidity spaces like bathrooms and needs protection against harsh dry drafts to maintain its soft foliage.",
    height: '12" - 18" drop',
    pot: '8" Basket',
    light: "Filtered / Shaded",
    water: "Never allow to fully dry",
  },
  haworthia: {
    title: "Haworthia",
    price: 15,
    img: "img/Haworthia.jpg",
    category: "succulents",
    desc: "Charmingly petite zebra-striped succulent forming tight rosettes of thick pointed leaves. Highly valued for remaining small and manageable, making it fantastic for sunny desktop configurations or terrariums.",
    height: '3" - 5" tall',
    pot: '3" Diameter',
    light: "Bright Indirect / Direct",
    water: "Minimal moisture",
  },
  "sedum-rubrotinctum": {
    title: "Sedum Rubrotinctum",
    price: 12,
    img: "img/Sedum.jpg",
    category: "succulents",
    desc: "Whimsical creeping succulent famously referred to as the jelly bean plant. Its glossy rounded leaves display bright jade colors that dramatically blush into deep crimson tips when exposed to strong open sunshine.",
    height: '4" - 6" trail',
    pot: '4" Diameter',
    light: "Full direct sun",
    water: "Dry desert style",
  },
  alocasia: {
    title: "Alocasia Polly",
    price: 35,
    img: "img/Alocasia-Polly.jpg",
    category: "tropical",
    badge: "New Arrival",
    desc: "Striking tropical species showcasing shield-shaped leaves accented by heavy metallic silver veins and wavy margins. An exotic centerpiece that immediately draws visual focus in high-end interiors.",
    height: '12" - 16" tall',
    pot: '6" Diameter',
    light: "Bright filtered light",
    water: 'Water when top 1" dries',
  },
  "nepenthes-rajah": {
    title: "Nepenthes Rajah",
    price: 85,
    img: "img/Nepenthes-Rajah.jpg",
    category: "carnivorous",
    badge: "Sale -20%",
    desc: "Magnificent exotic carnivorous pitcher plant highly sought after by premium collectors. It develops spectacular crimson traps hanging off leaf tendrils designed to hold fluids and capture insects in damp terrarium setups.",
    height: '8" - 12" wide',
    pot: '6" Net basket',
    light: "Filtered bright light",
    water: "Pure pure water only",
  },
  "begonia-amphioxus": {
    title: "Begonia Amphioxus",
    price: 25,
    img: "img/Begonia-Amphioxus.jpg",
    category: "tropical",
    desc: "Rare exotic specimen displaying narrow pointed butterfly leaves completely speckled with vivid crimson dots. Requires enclosed humid atmospheres like glass domes or vivariums to successfully flourish.",
    height: '6" - 10" tall',
    pot: '4" Diameter',
    light: "Medium dappled shade",
    water: "Constant light dampness",
  },
  "calathea-musaica": {
    title: "Calathea Musaica",
    price: 35,
    img: "img/Calathea-Musaica.jpg",
    category: "tropical",
    desc: "Intricate tropical foliage plant possessing a highly unusual network of fine mosaic checkerboard line patterns on light green leaves. Far sturdier than typical calatheas, it gracefully elevates plant shelves.",
    height: '10" - 14" tall',
    pot: '6" Diameter',
    light: "Medium shade indirect",
    water: "Keep uniformly damp",
  },
  "euphorbia-tirucalli": {
    title: "Euphorbia tirucalli",
    price: 30,
    img: "img/Euphorbia-tirucalli.jpg",
    category: "succulents",
    desc: "Striking succulent shrub composed of coral-like cylindrical pencil branches growing upwards. Turns bright shades of yellow, orange, and fiery red at the tips when given intense, unfiltered direct greenhouse light.",
    height: '18" - 24" tall',
    pot: '6" Diameter',
    light: "Intense direct sun",
    water: "Sparingly adaptive",
  },
  tillandsia: {
    title: "Tillandsia",
    price: 10,
    img: "img/Tillandsia.jpg",
    category: "tropical",
    desc: "Fascinating true air plant that grows naturally without soil substrates. Absorbs moisture directly through tiny silver scales covering its sculptural leaves. Simply dunk in filtered containers once a week.",
    height: '4" - 6" size',
    pot: "Mounted / Free",
    light: "Bright indirect air",
    water: "Weekly bath dunk",
  },
  fockea: {
    title: "Fockea",
    price: 45,
    img: "img/Fockea.jpg",
    category: "succulents",
    desc: "Unique caudiciform plant forming a rough swelling base structure designed to retain precious moisture reserves. Slender vine branches spill outwards from the top center, making it a masterpiece choice for collectors.",
    height: '8" - 12" base tall',
    pot: '6" Shallow clay',
    light: "Bright sun focus",
    water: "Dry down completely",
  },
};
